export default [
    {
        id: 1,
        title: "Project Manage",
        company: "Apple, Inc.",
        logo: "https://i.pinimg.com/originals/92/89/85/928985a51f4eb99c1f102eae73ed964b.jpg",
        type: "Fulltime",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 10000,
        location: "Silicon Valley",
        country: "California"
    },
    {
        id: 2,
        title: "Full Stack Developer",
        company: "Google",
        logo: "https://blockworks.co/wp-content/uploads/2021/02/shutterstock_552493603.jpg",
        type: "Fulltime",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 13500,
        location: "San Francisco",
        country: "USA"
    },
    {
        id: 3,
        title: "Web Developer Intern",
        company: "JP Morgan Chase",
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt-Uvx5Y6sHvGcAAmI9bv-AY1WF5BQOsm6KIEvZRBCk9TtsEV_3SO6RM7-FqCwLCPOLgA&usqp=CAU",
        type: "Internship",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 2500,
        location: "New York",
        country: "USA"
    },
    {
        id: 4,
        title: "Project Manager",
        company: "Meta Platforms, Inc.",
        logo: "https://fdn.gsmarena.com/imgroot/news/21/10/facebook-is-meta/-1200/gsmarena_101.jpg",
        type: "Part-time",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 8000,
        location: "Remote",
        country: "Netherlands"
    },
    {
        id: 5,
        title: "Data Analyst",
        company: "Netflix, Inc.",
        logo: "https://cdn.vox-cdn.com/thumbor/_nWIeNTPsYAOTtv9uwiHUxwWpbo=/0x0:3000x2000/1400x933/filters:focal(1260x760:1740x1240):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/70770729/ArielDavis_210629_ecl1087_Netflix_0001.0.jpg",
        type: "Fulltime",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 9000,
        location: "London",
        country: "United Kingdom"
    },
    {
        id: 6,
        title: "SWE Intern",
        company: "Amazon Web Services",
        logo: "https://pythian.com/wp-content/uploads/2021/08/Partners_AWS_Level2.png",
        type: "Internship",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 3000,
        location: "Online",
        country: "Germany",
    },
    {
        id: 7,
        title: "Project Manager",
        company: "Apple, Inc.",
        logo: "https://ijunkie.com/wp-content/uploads/2019/11/Apple-Logo.jpg",
        type: "Fulltime",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 10000,
        location: "Silicon Valley",
        country: "California",
    },
    {
        id: 8,
        title: "Junior F/E Developer",
        company: "Accenture Nordic",
        logo: "https://yt3.ggpht.com/ytc/AKedOLRFD3b0lhNNb28FTlwqG5EpJEfCzqLsUYrjuweCIQ=s900-c-k-c0x00ffffff-no-rj",
        type: "Part-time",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Soluta hic possimus natus distinctio recusandae voluptatem tenetur ipsa eligendi perferendis, quo voluptatibus molestiae veritatis, doloremque facilis!",
        salary: 6000,
        location: "Budapest",
        country: "Hungary",
    }
]